stages:

  status:
    cmd: bash src/01_status.sh
    outs:
      - download/toxrefdb_status.html

  download: 
    cmd: python3 src/02_download.py
    deps:
      - download/toxrefdb_status.html
      - src/02_download.py
    outs:
      - download/toxrefdb.dump

  build: 
    cmd: bash src/03_build_sqlite.sh
    deps:
      - download/toxrefdb.dump
      - src/03_build_sqlite.sh
    outs:
      - brick/toxrefdb.sqlite
